language: python
python:
  - "2.7"

env:
  - ANSIBLE_HOST_KEY_CHECKING=False

script:
  - echo "Run test scripts here"

before_deploy:
  - pip install ansible shade

deploy:
  - provider: script
    script: "ansible-playbook .playbook.yml"
    on:
      branch: master

